INSERT INTO [dbo].[Alphabet]
           ([UniqueId], [Russian], [English], [Examples])
VALUES
           (NEWID(), N'А', 'A', 'ah,father'),
		   (NEWID(), N'Б', 'B', 'bed,banana'),
		   (NEWID(), N'В', 'V', 'veh,vah-dah'),
		   (NEWID(), N'Г', 'G', 'geh'),
		   (NEWID(), N'Д', 'D', 'dohm'),
		   (NEWID(), N'Е', 'YE', 'yes,yel'),
		   (NEWID(), N'Ё', 'YO', 'yo,yogurt'),
		   (NEWID(), N'Ж', 'ZH', 'pleasure,measure'),
		   (NEWID(), N'З', 'Z', 'zebra'),
		   (NEWID(), N'И', 'I', 'ee,see'),
		   (NEWID(), N'Й', 'Y', 'boy,yogurt'),
		   (NEWID(), N'К', 'K', 'kite'),
		   (NEWID(), N'Л', 'L', 'love'),
		   (NEWID(), N'М', 'M', 'mama'),
		   (NEWID(), N'Н', 'N', 'nice'),
		   (NEWID(), N'О', 'O', 'go'),
		   (NEWID(), N'П', 'P', 'pen'),
		   (NEWID(), N'Р', 'R', 'rye'),
		   (NEWID(), N'С', 'S', 'sun'),
		   (NEWID(), N'Т', 'T', 'tor'),
		   (NEWID(), N'У', 'U', 'oo,soon'),
		   (NEWID(), N'Ф', 'F', 'find'),
		   (NEWID(), N'Х', 'KH', 'khak,loch'),
		   (NEWID(), N'Ц', 'TS', 'tseh,hats'),
		   (NEWID(), N'Ч', 'CH', 'church'),
		   (NEWID(), N'Ш', 'SH', 'shoe'),
		   (NEWID(), N'Щ', 'SHCH', 'shoe (but softer)'),
		   (NEWID(), N'Ъ', '', 'Hard sign that doesnt have a sound of its own but affects the preceding consonant'),
		   (NEWID(), N'Ь', '', 'Soft sign that also affects the preceding consonant and making it soft'),
		   (NEWID(), N'Ы', 'Y', 'mixture of ih and ee'),
		   (NEWID(), N'Э', 'E', 'eh,met'),
		   (NEWID(), N'Ю', 'YU', 'yoo,you'),
		   (NEWID(), N'Я', 'YA', 'ya,yard');
